name: docker-image-build

on: [push, pull_request]

jobs:

  build:
 
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7] 
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        # We use ppa:projectatomic repo to install podman
        sudo add-apt-repository -y ppa:projectatomic/ppa
        sudo apt install podman -y
    - name: Print podman version
      run: |
        podman -v
    - name: Build the Docker image
      run: podman build . --file Dockerfile --tag my-image-name:$(date +%s)
